### ISSUE TITLE
Port forward Server

### ISSUE THREAD

**Issue by lilRufi** [howardchung/watchparty#112]
My redis server is on 0.0.0.0 and I forwarded the app from my router. I can get signal with port checker apps but when I try to go to on my-ip:8080, It gives me error! Oh and my main server can't getting signal too.

**Comment by lilRufi** [comment]
I've configured the REACT_APP_SERVER_HOST in dotenv. In dev tools It's giving 404 error.

**Comment by howardchung** [comment]
Will need more information about what part isn't working.

Does the React app load but it can't talk to the server? (e.g. my-ip:3000 works but can't create rooms etc).

When you run the server with npm run dev does it say it can't bind to 8080?

**Comment by lilRufi** [comment]
localhost:8080 is working but my-ip:8080 is not working

I'm talking about npm run dev

**Comment by howardchung** [comment]
Hmm, that seems to be related to your specific router setup and probably not related to the application code. I generally recommend running this on a cloud server where port forwarding/firewall issues are less of a problem.

You can see if you are able to run other servers, or try changing the port

**Comment by lilRufi** [comment]
I can run other all my servers but even If I change my server port It stills not responding but thanks for help!

**Comment by howardchung** [comment]
You should be visiting my-ip:3000 for the UI. :8080 is just the backend server and will not render a web page

**Comment by howardchung** [comment]
but you will need to forward both ports

**Comment by lilRufi** [comment]
backend server is not working as I said I think

**Comment by lilRufi** [comment]
I forward both ports and both ports have a signal
