### ISSUE TITLE
Allow logged in users to create persistent rooms

### ISSUE THREAD

**Issue by bdbch** [howardchung/watchparty#12]
First of great project @howardchung! I'm a user of cytube right now and me and my friends enjoy watching videos from then to then.

Biggest issue is switching between Cytube and Discord when we want to watch non-youtube content together and I think the vBrowser solution is great!

I think having the option to create 1 persistent room which can be password or whitelist protected would be an awesome feature (and possibly could be a premium feature for more than one room).

What are your thoughts on this?

**Comment by howardchung** [comment]
Definitely could be something to look into if there's demand. Currently the security model is just temporary sessions protected by secret URLs, so we'd have to add some kind of protection if we're adding persistent rooms. Probably to avoid fiddling with passwords (and the associated security issues) a Discord-like invite link model would work best.

Also we'll need to add postgres, as right now only redis is used and that's just to make rooms survive server restarts.

**Comment by howardchung** [comment]
Thoughts on this so far:
* Allow a logged-in user to toggle a setting to make a room persistent. This user becomes the "room owner".
  * We just make Redis not expire these keys. Writing a persistent copy to postgres could be added later.
* (maybe sub only feature) Allow the room owner to set a vanity url (e.g. watchparty.me/r/MyAwesomeRoom)
  * anyone with this vanity URL can join the room (same as Discord)
* allow room owner to clear chat in permanent rooms
* allow room owner to unpermanent/delete the room
* (maybe) add kick/mute controls to prevent people from joining random rooms with common vanity URLs?

**Comment by howardchung** [comment]
Sub features:
* Increase limit of rooms claimed (1 to 5?)
* Allow setting vanity names
