### ISSUE TITLE
Make chat links clickable

### ISSUE THREAD

**Issue by howardchung** [howardchung/watchparty#157]

**Comment by KandarpAjvalia** [comment]
@howardchung hi, is there any specific format I should follow before I start working on this?

**Comment by howardchung** [comment]
How are you planning to implement this? I think we can regex for things like that look like links (start with http:// or https://) and convert those to clickable links.

However I think we'll have to be careful to avoid XSS. If we allow user content in the href attribute that might execute arbitrary JS.

**Comment by howardchung** [comment]
we might be ok if we enforce only taking http strings, since the classic attack vector here is to execute javascript: strings
