### ISSUE TITLE
No video for invitees

### ISSUE THREAD

**Issue by SammmyAhmad** [howardchung/watchparty#162]
I hosted a room, i can hear the audio and see the video. While the people i shared the link with, were operating Chrome on windows10, 8 and chrome for android mobile phones, They could hear the audio, see the subtitles, but not the video. 

What could be a reason?

**Comment by howardchung** [comment]
Which watch method did you use?

**Comment by SammmyAhmad** [comment]
Via file. 
File I had downloaded on my PC.

**Comment by howardchung** [comment]
Chrome 88+ currently has a problem with file sharing. You can turn off hardware acceleration in Chrome settings as a workaround.

**Comment by SammmyAhmad** [comment]
Okay. Thank you. Will try and get back, if it doesn't work.

**Comment by SammmyAhmad** [comment]
Worked for everyone after turning off host's hardware acceleration. Thank you. :D
