### ISSUE TITLE
Turning microphone on and off

### ISSUE THREAD

**Issue by axone13** [howardchung/watchparty#164]
After joining video calls, there is an option to toggle the webcam and mic. but when I try to turn them on and off, they usually don't work. especially the microphone.
I am using firefox 86.0 on windows 10 and the latest version of chrome on android and this problem occurs on both of them.

**Comment by howardchung** [comment]
Do you mean the button toggles but the audio/video isn't actually enabled/disabled?

Would you be able to check if this repros in Chrome desktop?

**Comment by axone13** [comment]
I have tested it on my laptop and also in chrome and the results were like so:
### Desktop chrome
The audio/video actually enable/disable but the buttons don't toggle until changing the tab to "Settings" or "Chat" and return back to "People".
### Desktop firefox
Buttons don't work and toggle at all and also firefox doesn't ask me to allow webcam/microphone when joining video call.

### Laptop firefox and chrome
The result was like "desktop chrome". It needs to change tabs to refresh the buttons state.

Tell me if you need more info. thanks

**Comment by axone13** [comment]
I mean the audio/video actually enable/disable but the buttons don't toggle until changing the tab to "Settings" or "Chat" and return back to "People".
At first, I thought the problem was with my browser but after testing this on a laptop and on pc with a USB webcam connected, I have noticed that as long as I don't have a connected webcam, the browser doesn't ask me to allow webcam/mic after joining video chat and buttons don't work and toggle at all but even after connecting the USB webcam, we need to change the tabs to refresh buttons states.

I think currently it's impossible to join video chats without a webcam (voice only). Anyway, buttons have a problem with refreshing states.

by the way, I have test it on chrome desktop and it was the same as others.

tell me if you need more info. thank you

**Comment by howardchung** [comment]
Thanks, yeah this looks like it's an issue where there is no video playing due to some weirdness with how we update states (the update is triggered by a timestamp update on the video).

I'll look into it.

You should be able to join video chat without a webcam. . . I checked in a fix for that a while back but I only have a laptop so I disabled the driver to simulate not having a webcam.

**Comment by axone13** [comment]
Thanks for your fix. buttons states are now update as expected.
but the second problem is still here. we can join video chats without webcam but we can't use microphone there. (microphone doesn't turn on)
could you take a look at that? thanks

**Comment by howardchung** [comment]
Checked in another to attempt audio only stream if no video is availble.
