### ISSUE TITLE
README improvements

### ISSUE THREAD

**Issue by bdbch** [howardchung/watchparty#17]
I think having better instructions on how to setup the project helps the repo to get traction and is helpful specially for beginners.

What do you think @howardchung?

**Comment by howardchung** [comment]
Sure, we could probably add a Quickstart section like odota/web and core have. Any other suggestions?

**Comment by bdbch** [comment]
How about also including an example on how to setup the VBrowser just so people can test the feature locally too?

**Comment by howardchung** [comment]
We could maybe do that but it's a little implementation-specific right now. It's also a bit fiddly with Let's Encrypt required to set up a secure connection and a separate instance to handle SSL termination. I originally tried to get individual certs for each VM but ran into rate limit issues.

Currently only Scaleway is supported as a cloud provider. It would be good to make that pluggable with different providers.

What would could do is something similar to odota where the UI can be configured to request from the production API so people don't need to set up the whole stack to work with it.

**Comment by bdbch** [comment]
If that is possible and doesn't bring to much load/pricing onto the production app it would be nice! If it's not possible we should just try to add some example instructions on how you set it up so if people want to replicate the feature locally (or selfhosted) they can still try it without support from our side.
