### ISSUE TITLE
site broken on ios

### ISSUE THREAD

**Issue by MfundoVala** [howardchung/watchparty#171]
video goes auto fullscreen. and video chat breaks application on safari. video chat only streams fullscreen. site is almost impossible to use.

**Comment by MfundoVala** [comment]
even when using chrome

**Comment by howardchung** [comment]
Can you specify which watch method you're trying to use? I'll also need to find an iOS device to test with. . .

**Comment by MfundoVala** [comment]
Regular link streaming

**Comment by howardchung** [comment]
Can you provide the video link? Is it YouTube or a URL?

**Comment by MfundoVala** [comment]
Url but it failed with any link I tried. On the iPhone 7 though.

**Comment by MfundoVala** [comment]
Hey Howard...

I really love your web and I think it would be even greater with the right
UX and UI design. Unfortunately I'm new to the react framework and am lost
on node too. I'm an extremely fast learner though.

But when I study materials out there it looks like you structure your apps
different to convention. Is this true or I just need to do more learning?

Regards

Mfundo

**Comment by howardchung** [comment]
It's a pretty standard create-react-app with a Node backend.

**Comment by howardchung** [comment]
video chat breaking the app should be fixed. Unsure about "video goes fullscreen" issue, if you could open a new issue with a more detailed description/video that would be great!
