### ISSUE TITLE
No Sound on receiver's end

### ISSUE THREAD

**Issue by Mithun162001** [howardchung/watchparty#211]
There has been no sound output on reciever's end even when the share audio is turned on in Chrome while screen sharing. Even when an external file is added there has been no sound in the receiver's end, only the person sharing is able to listen to sound. Please do check this issue. It's been persisting from past 7 days already.

**Comment by howardchung** [comment]
What browser is the receiver using? I could not repro this with chrome.

File sharing sound may depend on the codec used by the audio track.

**Comment by Mithun162001** [comment]
I have been using chrome

**Comment by howardchung** [comment]
Are both the sender and receiver using chrome?

**Comment by Mithun162001** [comment]
Yes

**Comment by Mithun162001** [comment]
The problem arised after the new release of chrome

**Comment by howardchung** [comment]
Can you check the version of Chrome being used at chrome://version?

**Comment by Mithun162001** [comment]
90.0.4430.93

**Comment by howardchung** [comment]
I tested on 90.0.4430.212 and it worked. Can you try sharing with yourself, i.e. open a second window and go into the same room and see if the audio works in that case?

**Comment by Mithun162001** [comment]
Yeah will check it once

**Comment by Mithun162001** [comment]
Yeah now it's working THANKS!!! 🎉🎇
