### ISSUE TITLE
configurable screenshare quality

### ISSUE THREAD

**Issue by howardchung** [howardchung/watchparty#22]
Currently capped at 720p, but some users might want higher resolution.

**Comment by bdbch** [comment]
Yes, screensharing quality is pretty bad while I tested it with a friend (compared to discord screensharing).

could we improve this?

**Comment by howardchung** [comment]
I encountered some lag issues when I tried it without capping the size, but you can test out changing the value here to 1080:
```
    const stream = await navigator.mediaDevices.getDisplayMedia({
      video: { cursor: 'never', width: 720, logicalSurface: true },
      audio: true,
    });
```

It's also possible that I just need to set up more TURN servers for relaying video.

**Comment by bdbch** [comment]
Are we using P2P here or is our server handling the video and provides it to the clients?

**Comment by howardchung** [comment]
It's using webRTC, so it tries to establish a p2p connection, but if it fails due to network conditions (NAT, proxies, etc.), it will relay the video traffic through a TURN server. (see iceServers).

I currently have one free one configured which will probably be a bottleneck at some point and we'll need to deploy additional ones.

**Comment by howardchung** [comment]
I've bumped this up, please report here if there are lag issues (or requests to make it even higher)
