### ISSUE TITLE
Add playlist feature

### ISSUE THREAD

**Issue by bdbch** [howardchung/watchparty#25]
I think just being capped to one video at a time is bad when you find another video but don't want to interupt the current video.

**Comment by howardchung** [comment]
Yeah, I think this would be useful!

**Comment by bdbch** [comment]
There are some open questions I'd have for this:

1. Who is the owner of the playlist? Can everybody add/remove videos?
2. Who can skip videos, reorder them?
3. Where should we show the playlist? Below the chat?

**Comment by howardchung** [comment]
Currently actions can be performed on the room by all members, so we'd probably keep that model for this. If rooms get bigger though we would probably want to add some kind of "host" role, so design with that in mind.

We would probably need to make it a popup/expandable piece of UI. I've tried to make the app fit on a single page without scrolling and would like to preserve that behavior if possible.

**Comment by bdbch** [comment]
@howardchung I started on this here:
https://github.com/howardchung/watchparty/pull/27

I also tried to refactor and clean up the room.ts class, what do you think? For the playlist itself I think we have to fetch the video data from youtube when someone adds a video to the playlist right? Otherwise we just have the video urls in the preview.

Also should the first video start autoplaying if no video is playing right now and do we have a way to find out if a video has ended?

I think it would be nice to have an auto play feature to skip to the next video automatically which can be toggled off/on via the UI so maybe you want to see video recommendations without automatically playing the next video.

**Comment by bdbch** [comment]
From what I'm seeing we could figure out the video length via the youtube API, then compare it with our videoTS on each timestamp update and when the video ended automatically set the next video to in the playlist to the current video, remove it from the array and play it.

**Comment by howardchung** [comment]
Yeah, we'd have to fetch the metadata from youtube.

I would say the the list should autoplay if there's no video playing now.

I believe there is an onended event that you can hook into: https://developers.google.com/youtube/iframe_api_reference

**Comment by howardchung** [comment]
But I think that's on the client so figuring out who detects the play end might be complicated. It would probably be easier to have the server compute timestamps.

**Comment by bdbch** [comment]
Yep, I think having multiple clients sending an end event would be complicated since we'd have to figure out on the server if and how many videos actually "ended" as maybe some client had a little delay or bad network when sending the socket message.

Since we have to fetch the metadata anyway we can just calc the end time on the serverside.

**Comment by bdbch** [comment]
> We would probably need to make it a popup/expandable piece of UI. I've tried to make the app fit on a single page without scrolling and would like to preserve that behavior if possible.

How about something like this using tabs for the chat/playlist view?
![chrome_bMYQPAf2TW](https://user-images.githubusercontent.com/6538827/82514831-02197f80-9b17-11ea-99b3-faac4df8d5d9.png)

Otherwise we'd have to look for a nice solution

**Comment by howardchung** [comment]
My initial thoughts were more integrating it with the "now watching" bar. Maybe a second button on it that opens up a playlist menu. Seems like it has more to do with the video than the chat, so that was my thinking.

I'm not dead set on any particular design though and could be convinced.
