### ISSUE TITLE
Trouble sharing video files

### ISSUE THREAD

**Issue by Cindyyyyw** [howardchung/watchparty#257]
The video is displaying a green image while the sound is playing normally without any issue.
Tried the other way around, my friend sees the green image on her end too.

Both are macOS users: MacBook Pro, iMac.
<img width="1242" alt="截屏2021-09-02 下午9 56 33" src="https://user-images.githubusercontent.com/85371547/131952521-701b9717-300a-4eb5-bde5-7843d8d92d98.png">

**Comment by howardchung** [comment]
Closing unless we can get a repro with a file
