### ISSUE TITLE
lint-staged fails when editing unsupported prettier file

### ISSUE THREAD

**Issue by howardchung** [howardchung/watchparty#29]
Apparently this won't work if a non-supported file is passed to prettier.

We can either whitelist extensions (as in the original change), just run on everything (might be ok), or turn off running prettier on commit. I'm not super opposed to just running it with `npm run prettier` when we want to do a formatting pass.

**Comment by bdbch** [comment]
I'd rather add a whitelist then, how about just sticking to typescript, ts, css and json files for now?

**Comment by howardchung** [comment]
and html
