### ISSUE TITLE
Disable a room when no one is in it

### ISSUE THREAD

**Issue by bdbch** [howardchung/watchparty#31]
Right now a room will continue "existing" and the interval keeps running. I think when all users left from the room roster, the room could be set to "cold" which stops the interval and pauses the videos but keeps it open.

What do you think @howardchung ?

**Comment by howardchung** [comment]
I think the interval is a no-op if there's no one in the room since the emit won't have anyone to send to.

That said it's still running the function and using some memory. Would be good to get some numbers on the perf impact.
