### ISSUE TITLE
4:3 videos cause page to scroll

### ISSUE THREAD

**Issue by qaisjp** [howardchung/watchparty#320]
controls and subs require the page to be scrolled to be viewed (cutting off the top of the video)

![image](https://user-images.githubusercontent.com/923242/144769091-eec1df58-950e-452d-a1ba-2284fc3a9563.png)

bottom of page:

![image](https://user-images.githubusercontent.com/923242/144769251-38c28d1a-34ed-412e-8a40-284d2a771361.png)

**Comment by howardchung** [comment]
Checked in a sorta hack/fix for this by setting a max height for the video based on the other elements.
