### ISSUE TITLE
[Feature request] Can we have a notification indication (bubble) on chat tab if you are on People tab and receive a new chat

### ISSUE THREAD

**Issue by mubeennetomi** [howardchung/watchparty#350]

**Comment by howardchung** [comment]
There is a sound indicator, do you also want a visual one?

**Comment by mubeennetomi** [comment]
<img width="737" alt="Screenshot 2021-12-30 at 4 43 45 PM" src="https://user-images.githubusercontent.com/94553042/147747275-9a771eb1-6493-4970-8035-356ffca4f958.png">

I mean some indicator like this when a new chat is received and you are on the video tab so cant see the chat
