### ISSUE TITLE
Screenshare and video calls are broken.

### ISSUE THREAD

**Issue by jacobvd0** [howardchung/watchparty#356]
Screensharing and video calls are not working on your official instance. They are also not working on my selfhosted instance.

**Comment by howardchung** [comment]
I can't repro this--this is probably a WebRTC/TURN issue. (maybe your network doesn't allow connecting to our servers)

**Comment by jacobvd0** [comment]
Ah, alright. I believe I found a fix to this. Thanks for the help.
