### ISSUE TITLE
document createRoom API

### ISSUE THREAD

**Issue by howardchung** [howardchung/watchparty#39]
For allowing integrations to create/launch rooms with specific videos set.

We already have a createRoom endpoint, although it currently doesn't auto-set a video.

**Comment by howardchung** [comment]
@albertcui:

The createRoom endpoint now supports calling it with a video in the POST body, e.g.
```
    const response = await window.fetch(serverPath + '/createRoom', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        video:
          'https://upload.wikimedia.org/wikipedia/commons/a/a5/Spring_-_Blender_Open_Movie.webm',
      }),
    });
```

It returns JSON with the name of the created room. I don't plan on writing docs for this until it's needed by more people, but I'll keep this issue open.

**Comment by justchokingaround** [comment]
@howardchung is there an endpoint to add a video to an existing room?

**Comment by howardchung** [comment]
Not currently. You can only create a new room with a specific video.

**Comment by justchokingaround** [comment]
oh ok. is there a possibility of having that feature added, or does it require more effort than necessary?

**Comment by howardchung** [comment]
It is a little more complicated than creating a new room since it requires checking for permissions (if the room is locked, we need to make sure the user can edit the video).

Can you explain a little more about your use case and what the API would enable?

**Comment by justchokingaround** [comment]
the use case is for a shellscript which allows users to select a movie/series and which would then create a watchparty room which would allow several people to watch it at the same time. the reason why i asked about adding a video to an existing room is for the case when a user watches a series with mutiple episodes, as to not having to create a new room each time a new episode is being played

**Comment by howardchung** [comment]
We do have a playlist feature--perhaps you could just add all the videos to the playlist and it'll auto-advance to the next one as the current video finishes?

**Comment by howardchung** [comment]
(I think we could include the playlist feature in the current API)

**Comment by justchokingaround** [comment]
that would be really nice

**Comment by howardchung** [comment]
Added the playlist support to the createRoom API

**Comment by justchokingaround** [comment]
thanks!
