### ISSUE TITLE
Show user mute status in video chat

### ISSUE THREAD

**Issue by howardchung** [howardchung/watchparty#455]
Currently the mute status isn't visible to others so it's not clear who's muted

**Comment by lwcorp** [comment]
Please reopen as there's still no mute status. You mute and unmute but it's not reflected (unlike play/pause).

**Comment by howardchung** [comment]
Tested the video chat and it seems to be fine

**Comment by lwcorp** [comment]
Here's a video capture of muting/unmuting a local file from my computer without any status change in the right side chat:

https://user-images.githubusercontent.com/1773306/215263214-921a00b5-ac39-4826-9201-a9104f815292.mp4

**Comment by howardchung** [comment]
I think you're mixing up the user video status with the playing video mute status. This issue refers to the video chat mute status.

Playing video mute status is a local setting and is not replicated to all participants in the room.

**Comment by lwcorp** [comment]
I do refer to the right side chat. If it shows "PAUSED THE VIDEO AT"/"STARTED THE VIDEO AT", why not "UN/MUTED THE VIDEO AT"?

**Comment by howardchung** [comment]
The right side chat is separate from the video chat (which is in the people tab).

In any case though, muted is not a global state like play/pause. So each user can mute/unmute themselves without changing it for everyone else--so it doesn't seem necessary to broadcast this to all users in the room
