### ISSUE TITLE
Remove the white overlay after subtitles/captions were uploaded

### ISSUE THREAD

**Issue by lwcorp** [howardchung/watchparty#510]
This screen remains even when it's already uploaded, making it a must to click anywhere else to escape it:
![image](https://user-images.githubusercontent.com/1773306/177050005-ae8c6865-b719-4514-99cf-b22833ad1f2a.png)

**Comment by howardchung** [comment]
The subtitle modal now contains a few configuration options so I think it's best to let the user close it manually.
