### ISSUE TITLE
Video.js (or other video player)

### ISSUE THREAD

**Issue by optix2000** [howardchung/watchparty#519]
Add Video.js or your modern html5 video player of choice.

This would give a few benefits:

- Support for DASH and HLS for dynamic bitrates
- Subtitle and audio track support

**Comment by howardchung** [comment]
I think we already support playing HLS streams, and subtitles are already supported?

Multiple audio tracks is interesting though, I was under the impression that the browser cannot read multitrack audio.

**Comment by howardchung** [comment]
What might be nice is the ability to play YouTube videos--perhaps then we can use a unified API rather than having separate code for video elements and YouTube + offer support for other platforms like Vimeo

**Comment by optix2000** [comment]
Weird, neither worked for me, but HLS worked on a test stream so might be an issue on my end.

Basic SRT subtitles work, but not ASS.

**Comment by howardchung** [comment]
I manually added support for converting SRT files to WebVTT which is what html5 uses. So any support for other formats would also need to go through a similar process.

I've done some testing with videojs on the videojs branch--but a significant amount of code would need to be rewritten to fully switch to videojs.

I also encountered a few potentially showstopping issues--e.g. the canplay event does not fire for youtube videos which causes the loading modal to stay stuck

**Comment by howardchung** [comment]
The recent refactor allows implementing new types of players and standardizes the API. It's possible that video.js etc. has additional features for regular HTML5 videos, but we could likely port that functionality rather than trying to integrate it into the existing code.
