### ISSUE TITLE
Failed to authenticate user when Making room permanent.

### ISSUE THREAD

**Issue by DarthOreo** [howardchung/watchparty#534]
I am getting this error when  trying to "Make Room Permanent"

I am guessing this has to do with the FIREBASE_APP_SDK_CONFIG.  

Does this field need to be:  {"type": "service_account", "project_id": "watchparty-xxxxx","private_key_id": "2fcbaxxxxx",    etc 

Or is there a different format for it?

**Comment by howardchung** [comment]
It should be FIREBASE_ADMIN_SDK_CONFIG for the server side checker--possibly that's why you're having issues
