### ISSUE TITLE
Add neko project URL to FAQ

### ISSUE THREAD

**Issue by m1k1o** [howardchung/watchparty#547]
Hello,

I see this it uses [neko](https://github.com/m1k1o/neko) what is great. But I was not able to find any information about it on the page. Could it be added to e.g. FAQ?

I have also seen, that there is used some custom version. Maybe some of those features/changes could be added to upstream repository.

And also I see that you have copied whole neko client and maintained there. I understand, that when you first found neko around 2 years ago, there was no different solution but to copy and modify client. Today, however, we [export all components](https://github.com/m1k1o/neko/blob/master/client/src/lib.ts) so neko can be embedded to other pages. Maybe worth refactoring for the future, as it would take away sigificant overhead of maintainig it as duplicate by you.

Very nice project and I really like to see neko being used beyond its own client!

**Comment by howardchung** [comment]
I've added a link to the neko repository in the README under the virtual browser section. Thanks for maintaining neko!
