### ISSUE TITLE
Error with recaptcha

### ISSUE THREAD

**Issue by DerKartdomi** [howardchung/watchparty#560]
I wanted to setup google recaptcha but I get some errors on my site. Can sonemone help me?

About the error:
Uncaught (in promise) TypeError: googleReCaptchaProps.executeRecaptcha is not a function  (VBrowserModal.tsx:49)
and
<GoogleReCaptchaProvider /> recaptcha key not provided (utils.ts:199) but I added it to .env

**Comment by howardchung** [comment]
Did you try with the latest version of recaptcha? Seems like a problem with either reading the key or installing an old version of the library
