### ISSUE TITLE
Mp4 with audio in 5.1 format not working on recieving end

### ISSUE THREAD

**Issue by UnderKoen** [howardchung/watchparty#592]
When using a video which uses 5.1 audio, the other user in the party don't hear all channels (mostly not voices). When using FFMPEG to convert the audio to stereo it does work. 

It would be nice if this process would not be needed.

**Comment by howardchung** [comment]
Unfortunately I think this is a browser limitation--but possibly could be fixed in the future with the correct WebRTC settings + browser support.

(you can test this by trying to play the video using your browser directly--if you also don't hear the audio there it won't be shareable via WatchParty)

**Comment by UnderKoen** [comment]
The file does work in the browser and on watchparty for the person who shares the file. But only on receiving browser it does not work.

**Comment by howardchung** [comment]
Interesting--in that case there may be some WebRTC tweak to make it possible to share all the channels

**Comment by howardchung** [comment]
mistagged in the commit but it's this one: https://github.com/howardchung/watchparty/commit/d6d62050b14d9afdaf3ccd48ffcf7b602a75d2cd
