### ISSUE TITLE
add self-service link to discord account for subscribers

### ISSUE THREAD

**Issue by howardchung** [howardchung/watchparty#63]
This will allow setting the subscriber role automatically. Might require integration with the Discord API on the server.

**Comment by Argn0** [comment]
I'm working on this. Is a Discord bot ok? Not sure if there is another way.

**Comment by Argn0** [comment]
I think I'll be using discord.js

**Comment by howardchung** [comment]
Discord bot is fine, we can add it to the channel and add config to control it from the watchparty server
