### ISSUE TITLE
How much server resource is needed for the browser session

### ISSUE THREAD

**Issue by Latrolage** [howardchung/watchparty#663]
How powerful does the server have to be for decoding for example a youtube video in the virtual browser sessions and encoding uploading the whole screen for each user to see?

**Comment by howardchung** [comment]
I would suggest at least 2 CPUs and 2GB RAM.

**Comment by Latrolage** [comment]
What is the config for `FIREBASE_ADMIN_SDK_CONFIG` supposed to look like? I got mine from https://console.firebase.google.com/project/PROJECT_NAME/settings/serviceaccounts/adminsdk and then the .json which you get from pressing "generate new private key" but when i use JSON.stringify() on it and put it after `FIREBASE_ADMIN_SDK_CONFIG=` in the ` .env` file it gives me "Invalid PEM formatted message."

**Comment by howardchung** [comment]
I think it's a non-escaped JSON string. So you probably don't need to stringify it

**Comment by Latrolage** [comment]
When I don't stringify it it tells me 

```
❯ PORT=4101 npm run dev

> watchparty@0.1.0 dev
> ts-node-dev --respawn --transpile-only --project server/tsconfig.json server/server.ts

[INFO] 09:53:25 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.9.4)
[VMWORKER] starting background jobs for availableListDockerUSLarge
[VMWORKER] starting background jobs for availableListDockerUS
vmWorker listening on 3100
Error: Cannot parse privateKey: Unsupported key format
    at Client.connect (/home/watchparty/watchparty/node_modules/ssh2/lib/client.js:146:13)
    at connect (/home/watchparty/watchparty/node_modules/ssh-exec/index.js:53:12)
    at /home/watchparty/watchparty/node_modules/ssh-exec/index.js:111:7
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
[ERROR] 09:53:27 Error: Cannot parse privateKey: Unsupported key format
```
