### ISSUE TITLE
Clicking Pause causes a mute (but clicking Play doesn't cause an unmute)

### ISSUE THREAD

**Issue by lwcorp** [howardchung/watchparty#681]
Fixing #509 caused a new issue - pausing causes a **mute**.
Every time you pause it mutes.
But every time you play it doesn't unmute.

Can you please not mute if the user didn't choose to mute? Also see #455 (which shouldn't be closed).

**Comment by howardchung** [comment]
I can't seem to repro this--are you watching a YouTube video or URL or something else?

**Comment by lwcorp** [comment]
Just a local file from my computer. Here's a video capture showing this:

https://user-images.githubusercontent.com/1773306/215263053-9d748804-0a72-4687-b683-c2497e287bff.mp4

**Comment by howardchung** [comment]
Interesting, I think this only happens with file shares. I think it's related to the auto-muting when screensharing that I added a little while back
