### ISSUE TITLE
protobowl.com integration?

### ISSUE THREAD

**Issue by jpbranson** [howardchung/watchparty#7]
You might have a better system already, but have you thought about possibly integrating with [protobowl.com](https://protobowl.com)? It has a system for generating/joining rooms, as well as a ton of questions from quizbowl-type competitions.

I don't know enough to know how easy it would be, so feel free to discard. The Github is [here](https://github.com/neotenic/protobowl).

**Comment by howardchung** [comment]
Funnily enough I've been working on building a version of Jeopardy using this code. I don't know if I'll merge it since it's kind of different from the rest of the functionality, but I was reusing a lot of the same room code so I just made it a new branch.

**Comment by howardchung** [comment]
You can test it out at https://jeopardy.watchparty.me/

I may split out that code into a different repo at some point (and maybe get it its own domain name)
