### ISSUE TITLE
LXD/LXC container?

### ISSUE THREAD

**Issue by foobazbar123** [howardchung/watchparty#70]
I saw the recommendation of a Docker deployment, but I'd like to suggest LXD/LXC as a possibility. Has all of the advantages of a Docker situation, but minus the "random layers" issues Docker can bring to the table.

If it sounds like something interesting, I might be willing to pitch in and help develop the image :)

**Comment by howardchung** [comment]
Sure, if you'd like to work on that I'd be happy to accept config files for LXD/LXC (I haven't worked with it before so not sure what's needed).

Currently the main watchparty app doesn't use Docker, so that Dockerfile doesn't exist yet (also would accept a PR to add one). The virtual browser instances do run in Docker containers.

**Comment by foobazbar123** [comment]
One can either do LXC/LXD as an image, ala'docker or as a profile one can import and then spawn a container, similar to how a Dockerfile works.

How do the virtual browser instances work? While one can run a docker container inside an LXD container, it isn't the most ideal thing to do. Turtles all the way down, as it were. Getting a node app up in LXD is pretty trivial, I have several running right now actually, so that's not an issue. The only thing missing in the documentation are the bits to make the virtual browser part go so that'd be needed to get the whole thing working

**Comment by howardchung** [comment]
For self-hosted users, this VM manager (https://github.com/howardchung/watchparty/blob/master/server/vm/docker.ts) expects to be pointed at a host that has Docker installed. (This host can be the same one that's running the node app) It'll connect to it via SSH (you provide a base64 encoded SSH private key) and run Docker to start a virtual browser.

So you could run it within the same LXD environment as the main node app, or if you have access to multiple VMs (or want to scale out), let the VM manager deploy Docker containers on separate hosts.

**Comment by foobazbar123** [comment]
Ah, I see. Hmmm... looks like you're wrapping around Neko which is cool. I wonder how hard it would be to swap out docker for pure LXD. This could have advantages in the management as it would eliminate any need to SSH to anywhere at all. One could just call LXD directly to spawn N containers and let LXD handle the authentication/authorization issues. May ponder that some. I may work on this some this weekend and get back to you :)

**Comment by howardchung** [comment]
Won't you still need some kind of LXD client/server setup, if the two machines are on different networks? (can you even LXD over the internet?)

**Comment by foobazbar123** [comment]
Short answer, yes. Longer answer, it depends on what you mean by "lxd over the internet". Though, really I suppose it doesn't matter what you mean haha. You can admin an LXD host over the internet, locally, or via the LAN. Authentication is certificate based and you can get pretty fancy with how you do it.

The basic thing goes something like this though:

lxc remote add YourCoolName https://FQDN

Where FQDN is local, LAN, or Internet

Once you do that, you can "lxc list" or "lxc launch" or even "lxc exec YourCoolName bash" to your heart's content

**Comment by foobazbar123** [comment]
To clarify, the full commands would be something like:

"lxc list YourCoolName:" or "lxc launch SomeImage YourCoolName:<name if you want to specify one>" or "lxc exec YourCoolName:YourAmazingContainer bash"

**Comment by howardchung** [comment]
Docker also has an API, but the cert authentication for that sounded like a pain to set up so that's why I went with SSH.

If you want to investigate and figure out something that works for LXD, that would be great! You could probably implement a LXD version of the docker.ts file to deploy vbrowsers via LXD.

If you want to do that for the main app as well, you can, but since it's a simple node app it's already pretty easy to deploy. I would also probably lean toward using Docker for the main app as it's kind of the de-facto standard for containerized web apps.

**Comment by howardchung** [comment]
I updated the browser version, modified some of the policies, default extensions, encoder settings, etc. I think standard neko worked fine too, I just wanted control over some small things.

Not sure what you mean by embedding here. If you mean getting the browser into the web page, it's just a video stream connected over webrtc (neko acts as a webrtc peer). That's separate from the provisioning and VM management which is what docker.ts does. Both the neko client and the watchparty client are examples of how to connect the browser to the VM.
