### ISSUE TITLE
Youtube not working

### ISSUE THREAD

**Issue by lay3r** [howardchung/watchparty#828]

**Comment by howardchung** [comment]
Do you have a sample Youtube link that's not working? I just tested one and it seemed fine

**Comment by lay3r** [comment]
> Do you have a sample Youtube link that's not working? I just tested one and it seemed fine

https://youtu.be/TJ2ifmkGGus?feature=shared

**Comment by lay3r** [comment]
I think you have to use regex to parse youtube video id

**Comment by howardchung** [comment]
It works if the ?feature=shared bit is removed--looks like the current code doesn't like URL parameters
