### ISSUE TITLE
It doesn't stream mkv files on firefox.

### ISSUE THREAD

**Issue by khebrati** [howardchung/watchparty#829]
the version hosted on watchparty.me isn't able to stream .mkv files one firefox desktop and gives this error: 
![Screenshot_20230915_203232](https://github.com/howardchung/watchparty/assets/131471493/162b2aad-2d2c-4fd0-8273-bef2ccdcf7f9)
I have tested with different sources, one of which was : 
https://test-videos.co.uk/vids/jellyfish/mkv/1080/Jellyfish_1080_10s_2MB.mkv

**Comment by howardchung** [comment]
File support is going to depend on browser and codec. You can try with a different browser such as Chrome or Edge
