### ISSUE TITLE
Sponsorblock appears to interfere with WatchParty

### ISSUE THREAD

**Issue by ayancey** [howardchung/watchparty#830]
When I am in a watchparty, if the Sponsorblock extension skips a segment, it doesn't show that I have seeked further in the video, and I become out of sync with everyone else. This applies to anyone else in the party who also has the extension installed.

**Comment by howardchung** [comment]
What are you watching? YouTube video or something else?

**Comment by oXyiGYJ** [comment]
> What are you watching? YouTube video or something else?

Sponsorblock requires you to add watchparty.me (or any other site if self hosted) as a Youtube Alternative to make it work outside of youtube.com. I am not sure if you are familiar with SponsorBlock @howardchung but that would be a nice addition to get it to work.

Not a huge deal, and might not even be possible, but this isnt an issue for you (in my opinion) as it requires the user to specifically state the URL as a YouTube alternative site for the extension to even work on the site to begin with.

**Comment by ayancey** [comment]
> > What are you watching? YouTube video or something else?
> 
> 
> 
> Sponsorblock requires you to add watchparty.me (or any other site if self hosted) as a Youtube Alternative to make it work outside of youtube.com. I am not sure if you are familiar with SponsorBlock @howardchung but that would be a nice addition to get it to work.
> 
> 
> 
> Not a huge deal, and might not even be possible, but this isnt an issue for you (in my opinion) as it requires the user to specifically state the URL as a YouTube alternative site for the extension to even work on the site to begin with.

In this case, that's not true because it's an embed, right? Alternative sites are for invidious instances.

**Comment by howardchung** [comment]
I'm not sure how SponsorBlock is seeking to new timestamps, but we just listen to events emitted by the JS embed API to update the timestamp for everyone. If SponsorBlock doesn't cause those events to fire then that will cause the syncing not to update to everyone else

**Comment by oXyiGYJ** [comment]
I will test it out when I have a moment and report back if I find anything (not a dev, just constantly interested in different open source projects I use).

**Comment by ayancey** [comment]
Just to reiterate: having sponsorblock installed as an extension on one or more participants' browsers causes unexpected behavior.

However, native sponsorblock support in WatchParty would be awesome.

**Comment by oXyiGYJ** [comment]
> > > What are you watching? YouTube video or something else?
> > 
> > 
> > Sponsorblock requires you to add watchparty.me (or any other site if self hosted) as a Youtube Alternative to make it work outside of youtube.com. I am not sure if you are familiar with SponsorBlock @howardchung but that would be a nice addition to get it to work.
> > Not a huge deal, and might not even be possible, but this isnt an issue for you (in my opinion) as it requires the user to specifically state the URL as a YouTube alternative site for the extension to even work on the site to begin with.
> 
> In this case, that's not true because it's an embed, right? Alternative sites are for invidious instances.

@ayancey no, as mine does not detect a YouTube video on the site unless I set it as a 3rd-party site.

**Comment by ayancey** [comment]
Will test this and get back to you.

**Comment by ayancey** [comment]
> > > > What are you watching? YouTube video or something else?
> > > 
> > > 
> > > Sponsorblock requires you to add watchparty.me (or any other site if self hosted) as a Youtube Alternative to make it work outside of youtube.com. I am not sure if you are familiar with SponsorBlock @howardchung but that would be a nice addition to get it to work.
> > > Not a huge deal, and might not even be possible, but this isnt an issue for you (in my opinion) as it requires the user to specifically state the URL as a YouTube alternative site for the extension to even work on the site to begin with.
> > 
> > 
> > In this case, that's not true because it's an embed, right? Alternative sites are for invidious instances.
> 
> @ayancey no, as mine does not detect a YouTube video on the site unless I set it as a 3rd-party site.

I wasn't able to replicate the issue I had where it would skip segments, but it Sponsorblock definitely detects it, regardless of the 3rd party setting.

![firefox_uwdjVqpRj7](https://github.com/howardchung/watchparty/assets/10055792/c5804829-f308-4547-9acd-820fcc961ee8)
![firefox_wLURWQUoqA](https://github.com/howardchung/watchparty/assets/10055792/962f7d8f-88c1-4619-ab09-6f0ff8fb8c30)

Could be only a Firefox thing?

**Comment by oXyiGYJ** [comment]
No. I recently switched from Brave to Vivaldi and now it is working on WatchParty without me adding it.
