### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by dillfrescott** [howardchung/watchparty#835]
Could you please make an env variable to disable the auth and subscription features and just allow every user. This way I can put the app behind external auth and not have to use firebase. I'd much appreciate it!

**Comment by howardchung** [comment]
Good point, probably we shoudn't be doing those checks by default unless the appropriate env vars are present, rather than create an override

**Comment by dillfrescott** [comment]
Yes very much agreed. it would make things much simpler for me and other self hosters!

**Comment by howardchung** [comment]
Took a look through the code and there are two main categories of features that require auth.

Room management features:
We expect a validated UID here to assign owners to rooms/validate that it's really the owner making changes

VBrowser features:
We require login here to prevent abuse/check if a user is subscriber to allow large/region selection, but we don't actually do anything with the UID value.

Is there one of these that you care more about specifically? The second is is easier to make auth optional--I can make the first one default to some fake UID, but I'm concerned that will pollute the database if auth is turned on later.

**Comment by dillfrescott** [comment]
I am currently using the app without a database (besides redis) and am running into issues because i dont have firebase connected, skipping the popup for the vbrowser to start is essential for me.

Secondly, having an option to just disable auth and remove the sign in and subscribe buttons would be fantastic!

I also would like to support you for making these changes, so would purchasing premium on the main site work as a donation?

**Comment by howardchung** [comment]
Sounds like you only care about the second category then--since without a database you won't be able to use the permanent room management features anyway.

I can default the subscriber check to true (allowing large vbrowsers and region selection, although it's not clear if your self hosted instance supports these features) and allow vbrowser launching for anonymous users if firebase auth isn't set up.

And yes, a subscription would be much appreciated!

**Comment by dillfrescott** [comment]
Sounds good to me! I will subscribe within the hour.
