### ISSUE TITLE
Nodejs cluster

### ISSUE THREAD

**Issue by lay3r** [howardchung/watchparty#840]
Why are you using pm2 shards and not nodejs cluster?

**Comment by howardchung** [comment]
Pm2 has nicer logging and management features. But aside from that there's not much reason

**Comment by lay3r** [comment]
Then you have to look at the logs of each cluster

**Comment by lay3r** [comment]
On the other hand, pm2 will automatically restart the cluster, got you

**Comment by lay3r** [comment]
https://socket.io/docs/v4/pm2/

**Comment by howardchung** [comment]
Right now nginx handles the connections as a gateway and then delegates to the appropriate shard running on separate ports

**Comment by lay3r** [comment]
I can't figure out from your code how a client connects to the same socket session as another client in cluster mode. By the name of the room? Because I can't see sticky sessions.

**Comment by howardchung** [comment]
The SHARD parameter is computed from the room name and passed in the URL. Nginx handles directing the traffic to the correct port/instance

**Comment by lay3r** [comment]
What about connecting users to session through redis?

**Comment by howardchung** [comment]
That could probably work too but requires a dependency on Redis
