### ISSUE TITLE
Add a "Shut all vbrowsers button"

### ISSUE THREAD

**Issue by IFUCKINGHATEYOUALL** [howardchung/watchparty#841]
Many times ive seen "A vbrowser on this account is already opened" and i had too search through my whole entire  compute rhistory because i dont use the "Save room" button trying too find the vbrowser which is opened
PLUS sometimes none are even open

**Comment by howardchung** [comment]
We've made some improvements to hopefully reduce the number of orphaned vbrowsers. But ultimately the best way to handle this is to make sure to close each browser with the stop button.
