### ISSUE TITLE
bandwidth question

### ISSUE THREAD

**Issue by cyber-sec0** [howardchung/watchparty#843]
If I stream a local movie file of 1:30 hours and 3.0 GBs, will I use exactly 3.0 GBs of bandwidth?

If I register and stream it using a free account, will the bandwidth be lower? How much lower If I stream a local movie file of 1:30 hours and 3.0 GBs?

Do only paid accounts lower the bandwidth usage? How much lower If I stream a local movie file of 1:30 hours and 3.0 GBs?

**Comment by howardchung** [comment]
If you use the free option you will be uploading to each viewer so multiply by the number of viewers.

If you use the relay server, you will only be uploading to the relay server so it will be constant regardless of viewer count.

**Comment by cyber-sec0** [comment]
So since I am the one streaming a 3.0 GBs movie, I won't download 3.0 GBs from the movie, just upload 3.0 GBs from the movie for each viewer?

**Comment by howardchung** [comment]
Yes, your own video file will be used as the source for your own stream.
