### ISSUE TITLE
Disable notification sounds when the video is paused/played

### ISSUE THREAD

**Issue by cyber-sec0** [howardchung/watchparty#849]
There is no need to play a notification sound when the video is paused/played, because this is an action that is very easy to notice no matter what, videos usually have sound, which would call everyone's attention, so having a notification sound playing in both cases seems needless to me, or if we could at least disable "video interaction" sounds that would be nice.

**Comment by howardchung** [comment]
I think more generally this is just a case of the notification sound triggering because a new system event has been written to the log. We could probably just disable the sound unless it's a user chat message.
