### ISSUE TITLE
.MKV No Audio

### ISSUE THREAD

**Issue by katccat** [howardchung/watchparty#866]
Can't hear any audio from an mkv stream on a macbook. Audio doesn't work in any browser other than Safari where several Watchparty features don't function.

**Comment by howardchung** [comment]
This is probably due to unsupported AC3 audio codec in Chrome. You can try re-encoding the audio to AAC using handbrake or something. On Windows I think Edge supports decoding it but not sure if there's an equivalent for Mac

**Comment by howardchung** [comment]
The most reliable solutions is going to be re-encoding the file into h264/AAC for broadest support
