### ISSUE TITLE
Unable to upload media file on Firefox.

### ISSUE THREAD

**Issue by miou-gh** [howardchung/watchparty#96]
```js
Uncaught (in promise) TypeError: r.captureStream is not a function
    t App.tsx:575
    s runtime.js:45
    _invoke runtime.js:274
    t runtime.js:97
    Babel 6
    Lodash 4
    t Portal.js:129
    Lodash 4
    t Button.js:77
    React 12
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
App.tsx:575:29
    Babel 6
    Lodash 4
    t Portal.js:129
    Lodash 4
    t Button.js:77
    React 12
    bind_applyFunctionN self-hosted:1359
    Jt self-hosted:1322
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
    bind_applyFunctionN self-hosted:1359
    Yt self-hosted:1322
```

**Comment by howardchung** [comment]
Unfortunately a lot of the webrtc features have limited Firefox support due to its differences from Chromium. I'll leave this open to track the issue, but it's likely to take a fair amount of work/testing to make it compatible.

**Comment by howardchung** [comment]
Firefox still prefixes this method with mozCaptureStream due to the implementation being different. If they ever make it consistent and remove the prefix, this will just start working, but if not I don't think we have the bandwidth to test and write specific code for FF.
